name = "Curve25519Dalek"
version = "0.1.0"
keywords = ["formal verification"]
defaultTargets = ["Curve25519Dalek"]

[leanOptions]
pp.unicode.fun = true            # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
linter.mathlibStandardSet = true
maxSynthPendingDepth = 3
maxRecDepth = 10000

[[require]]
name = "aeneas"
git = "https://github.com/AeneasVerif/aeneas.git"
subDir = "backends/lean"
rev = "1b39931d"

[[require]]
name = "PrimeCert"
git = "https://github.com/b-mehta/PrimeCert.git"
rev = "15fd61770c9a893af0f5cb7893ea98b7d0bf8d52"

[[lean_lib]]
name = "Curve25519Dalek"

[[lean_lib]]
name = "Utils"

[[lean_exe]]
name = "listfuns"
root = "Utils.ListFuns"
supportInterpreter = true

[[lean_exe]]
name = "syncstatus"
root = "Utils.SyncStatus"
supportInterpreter = true
